[package]
name = "rest"
version = "2026.1.0"
authors = ["Igor Ying Zhang <igor_zhangying@fudan.edu.cn>"]
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
time = "0.1.12"
clap = "3.*"
regex = "1.*"
itertools = "0.15"
serde_json = "1.0"
serde = {version="1.0",features=["derive"]}
serde-inline-default = "1.0"
num = "0.4"
num-complex = "0.4"
libc = "0.2"
#hdf5 = "0.8.0"
hdf5-metno = "0.12"
chrono = "0.4"
#jemallocator = "0.3.2"
#mimalloc = "0.1.43"
rayon = "1.8"
crossbeam = "0.8"
libm = "0.2"
#blas-sys = "0.7"
#blas = "0.22"
lazy_static = "1.4"
toml = "0.8"
#tuple-conv = "1.0.1"
num-traits = "0.2.15"
rand = "0.9"
array_tool = "1.0.3"
fuzzy-matcher = "0.3.7"
#ndarray = "0.15.6"
# for libecpint
#cxx = "1.0"
#autocxx = "0.30.*"
#miette = "5.0"
#katex-doc = "0.1.0"
#rust_libecpint = {path="../rust_libecpint"}
# seems to pull in libssl and libcrypto which is rejected by manylinux
reqwest = { version = "0.10", default-features = false, features = ["blocking", "json", "rustls-tls"] }
mpi = {version = "0.8", features = ["user-operations", "derive"], optional = true}
# for cuda
#cudarc = "0.10.0"
rest_tensors = {path="../rest_tensors", default = false, features = []}
rest_libcint = {path="../rest_libcint"}
#liblbfgs = {path="../rust-lbfgs"}
liblbfgs = "0.1.0"
sysinfo = "0.33"
rstsr = { version = "0.7", default-features = false, features = ["openblas", "linalg", "rayon", "std", "col_major", "tblis"] }
rstsr-core = { version = "0.7", default-features = false }
rstsr-openblas = { version = "0.7", features = ["openmp"] }
tblis = { version = "0.2", features = ["dynamic_loading"] }
derive_builder = { version = "0.20" }
indexmap = { version = "2.14" }

dftd3 = { version = "0.2", optional = true }
dftd4 = { version = "0.2", optional = true }
libxc = { version = "0.1", features = ["api-v7_0", "dynamic_loading"] }
geometric-pyo3 = { version = "0.1.1", optional = true }

approx = "0.5"
log = "0.4"
env_logger = "0.11"

[build-dependencies]
dunce = "1.0"

[dependencies.pyo3]
version = "0.24.2"
features = ["generate-import-lib"]

#[package.metadata.docs.rs]
#rustdoc-args = [
#    "--html-in-header",
#    #".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
#    "/share/home/tygao/REST3.0/rest/katex.html",
#]

[dev-dependencies]
criterion = "0.4"

[features]
default = ["dftd3", "dftd4", "geometric-pyo3", "mpi"]
mpi = ["dep:mpi"]
dftd3 = ["dep:dftd3"]
dftd4 = ["dep:dftd4"]
geometric-pyo3 = ["dep:geometric-pyo3"]
openblas = []
intel-mkl = []
scalapack = ["rest_tensors/scalapack"]

#[[bench]]
#name = "bench_tensors"
#harness = false


[[bin]]
name = "rest"
path = "src/main.rs"

# for pyrest
[lib]
name = "pyrest"
path = "src/lib.rs"
crate-type=["cdylib","lib"]
