[ctrl]
     print_level =               1
     xc =                        "b3lyp"
     basis_path =                "def2-sv(p)"
     auxbas_path =               "def2-SV(P)-JKFIT"
     eri_type =                  "isdf"
     isdf_k = 			 6
     initial_guess =             "sad"
     charge =                    0.0
     spin =                      1.0
     spin_polarization =         false
     pruning =                   "nwchem"
     radial_grid_method =        "treutler"
     scf_acc_rho =               1.0e-5
     scf_acc_eev =               1.0e-5
     scf_acc_etot =              1.0e-6
     num_threads =               1
     abort_on_mem_exceed = 	 false

[geom]
     name = "NH3, example"
     unit = "angstrom"
     position = '''
             N  -2.1988391019      1.8973746268      0.0000000000,
             H  -1.1788391019      1.8973746268      0.0000000000,
             H  -2.5388353987      1.0925460144     -0.5263586446,
             H  -2.5388400276      2.7556271745     -0.4338224694
'''
