// use pyo3::types::PyDict;
// use pyo3::{Py, PyResult, Python};
use serde::{Deserialize,Serialize};
// use crate::geom_io::GeomCell;
// use crate::ctrl_io::InputKeywords;

#[derive(Debug,Clone,Serialize, Deserialize)]
pub struct GeomeTRIC {
    // convergence criteria
    pub maxiter              : i32,
    pub convergence_energy   : f64,
    pub convergence_grms     : f64,
    pub convergence_gmax     : f64,
    pub convergence_drms     : f64,
    pub convergence_dmax     : f64,
    // internal cordinate (IC) system
    pub coordsys : String,      // "cart", "prim", "dlc", "hdlc", "tric" (defualt), "tric-p"
    // job type options
    pub transition: bool,       // optimize a transition state, default is false
    pub irc: bool,              // find intrinsic reaction coordinate pathway starting from a transition state 
    pub irc_direction : String, // "forward", "backward", "both" (default)
    // Hessian and trust-radius algorithm options
    pub hessian: String,        // "never" (defalt for minimization), "first" (default for transition state and IRC),
                                //  "last", "first+last", "stop" (do not optimize), "each" (costly)
    pub reset: bool,            // Reset approximate Hessian to guess when eigenvalues are below epsilon;
                                //  default true for energy minimization, false for TS
    pub trust: f64,             // Starting value of the trust radius; default 0.1 Å
    pub tmax: f64,              // Maximum value of trust radius; default 0.3 Å
    pub tmin: f64,              // Minimum value of trust radius; default 1e-4
    pub epsilon: f64,           // Small eigenvalue threshold for resetting Hessian; default 1e-5
    pub subfrctor: i32,         // Project net force and torque from gradient: 0=never, 1=auto (default), 2=always;
                                //  useful for QM/MM systems where net torque causes spurious slow rotation
    pub usedmax: bool,          // Use max displacement component (instead of RMS) when applying trust radius;
                                //  suitable for systems with highly anisotropic force constants
    pub frequency: bool,        // perform a frequency and thermochemical analysis whenever a Hessian calculation is requested; 
                                // default value is true
    pub thermo: [f64; 2],       // [Temperature, Pressure] 
    // output options
    pub prefix: String,         // Specify the base name of files and temporary folders generated by geomeTRIC
    pub verbose: i32,           // 0: concise and default, 1: normal, 2: verbose, 3: low-level function output
    // Hessian computation
    pub analytic_hessian: bool, // If true, use REST analytical Hessian instead of geomeTRIC numerical finite-difference
    pub use_analdrv: Option<bool>,  // Use analytical derivative module (analdrv) for Hessian computation.
                                    // Default None, which means usually uses driver `analdrv`; but if `[hessian]` section is present, then prefer `[hessian]` section.
                                    // If set to true, always use `analdrv` for Hessian computation; if set to false, always use `[hessian]` section.
    pub fac: Option<f64>,           // Multiplicative factor to covalent-radii criterion for bond detection
                                    // in geomeTRIC's build_topology (REST-internal, not forwarded to run_optimization).
                                    // Default None -> geomeTRIC default 1.2. Lower values (e.g. 0.9) prune spurious
                                    // long-range contacts such as ionic Sr-O in perovskite clusters, which sharply
                                    // reduces the number of redundant internal coordinates (distances/angles/dihedrals).
}

impl Default for GeomeTRIC {
    fn default() -> Self {
        GeomeTRIC {
            maxiter              : 300,
            convergence_energy   : 1.0e-6, // Eh
            convergence_grms     : 3.0e-4, // Eh/Bohr
            convergence_gmax     : 4.5e-4, // Eh/Bohr
            convergence_drms     : 1.2e-3, // Angstrom
            convergence_dmax     : 1.8e-3, // Angstrom
            coordsys : "tric".to_string(),
            transition: false,
            irc: false,
            irc_direction : "both".to_string(),
            hessian: "never".to_string(),
            reset: true,
            trust: 0.1,
            tmax: 0.3,
            tmin: 1.0e-4,
            epsilon: 1.0e-5,
            subfrctor: 1,
            usedmax: false,
            frequency: false,
            thermo: [300.0, 1.0],
            prefix: "GeomeTRIC".to_string(),
            verbose: 0,
            analytic_hessian: false,
            use_analdrv: None,
            fac: None,
        }
    }
}

impl GeomeTRIC { 
    pub fn to_toml(&self) -> toml::Value {

        let mut table = toml::map::Map::new();
        
        table.insert("maxiter".to_string(), toml::Value::Integer(self.maxiter as i64));
        table.insert("convergence_energy".to_string(), toml::Value::Float(self.convergence_energy));
        table.insert("convergence_grms".to_string(), toml::Value::Float(self.convergence_grms));
        table.insert("convergence_gmax".to_string(), toml::Value::Float(self.convergence_gmax));
        table.insert("convergence_drms".to_string(), toml::Value::Float(self.convergence_drms));
        table.insert("convergence_dmax".to_string(), toml::Value::Float(self.convergence_dmax));
        table.insert("coordsys".to_string(), toml::Value::String(self.coordsys.clone()));
        table.insert("transition".to_string(), toml::Value::Boolean(self.transition));
        table.insert("irc".to_string(), toml::Value::Boolean(self.irc));
        table.insert("irc_direction".to_string(), toml::Value::String(self.irc_direction.clone()));
        table.insert("hessian".to_string(), toml::Value::String(self.hessian.clone()));
        table.insert("reset".to_string(), toml::Value::Boolean(self.reset));
        table.insert("trust".to_string(), toml::Value::Float(self.trust));
        table.insert("tmax".to_string(), toml::Value::Float(self.tmax));
        table.insert("tmin".to_string(), toml::Value::Float(self.tmin));
        table.insert("epsilon".to_string(), toml::Value::Float(self.epsilon));
        table.insert("subfrctor".to_string(), toml::Value::Integer(self.subfrctor as i64));
        table.insert("usedmax".to_string(), toml::Value::Boolean(self.usedmax));
        table.insert("frequency".to_string(), toml::Value::Boolean(self.frequency));
        
        // 对于 thermo 数组，需要转换为 TOML 数组
        let thermo_array = toml::Value::Array(
            self.thermo.iter().map(|&x| toml::Value::Float(x)).collect()
        );
        table.insert("thermo".to_string(), thermo_array);
        
        table.insert("prefix".to_string(), toml::Value::String(self.prefix.clone()));
        table.insert("verbose".to_string(), toml::Value::Integer(self.verbose as i64));
        
        toml::Value::Table(table)

    }
}

pub fn parse_geometric_keywords(tmp_keys: &serde_json::Value) -> anyhow::Result<Option<GeomeTRIC>> { 
    match tmp_keys.get("geometric_pyo3").unwrap_or(&serde_json::Value::Null) {
        serde_json::Value::Object(tmp_ctrl) => {
            let mut geometric = GeomeTRIC::default();
            geometric.verbose = match tmp_ctrl.get("verbose").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(tmp_str) => {tmp_str.to_lowercase().parse().unwrap_or(0)},
                serde_json::Value::Number(tmp_num) => {tmp_num.as_i64().unwrap_or(0) as i32},
                other => {0},
            };
            geometric.prefix = match tmp_ctrl.get("prefix").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(s) => s.clone(),
                other => String::from("GeomeTRIC"),
            };
            // =====================================
            //  Keywords for convergence criteria 
            // =====================================
            geometric.maxiter = match tmp_ctrl.get("maxiter").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(tmp_str) => {tmp_str.to_lowercase().parse().unwrap_or(300)},
                serde_json::Value::Number(tmp_num) => {tmp_num.as_i64().unwrap_or(300) as i32},
                other => {300},
            };
            geometric.convergence_energy = match tmp_ctrl.get("convergence_energy").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(1.0e-6)},
                other => {1.0e-6},
            };
            geometric.convergence_grms = match tmp_ctrl.get("convergence_grms").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(3.0e-4)},
                other => {3.0e-4},
            };
            geometric.convergence_gmax = match tmp_ctrl.get("convergence_gmax").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(4.5e-4)},
                other => {4.5e-4},
            };
            geometric.convergence_drms = match tmp_ctrl.get("convergence_drms").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(1.2e-3)},
                other => {1.2e-3},
            };
            geometric.convergence_dmax = match tmp_ctrl.get("convergence_dmax").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(1.8e-3)},
                other => {1.8e-3},
            };
            geometric.coordsys = match tmp_ctrl.get("coordsys").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(s) => s.clone(),
                other => String::from("tric"),
            };
            geometric.transition = match tmp_ctrl.get("transition").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(s) => *s,
                other => false,
            };
            geometric.irc = match tmp_ctrl.get("irc").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(s) => *s,
                other => false,
            };
            geometric.irc_direction = match tmp_ctrl.get("irc_direction").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(s) => s.clone(),
                other => String::from("both"),
            };
            geometric.hessian = match tmp_ctrl.get("hessian").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::String(s) => s.clone(),
                other => String::from("never"),
            };
            geometric.reset = match tmp_ctrl.get("reset").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(s) => *s,
                other => true,
            };
            geometric.trust = match tmp_ctrl.get("trust").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(0.1)},
                other => {0.1},
            };
            geometric.tmax = match tmp_ctrl.get("tmax").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(0.3)},
                other => {0.3},
            };
            geometric.tmin = match tmp_ctrl.get("tmin").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(1.0e-4)},
                other => {1.0e-4},
            };
            geometric.epsilon = match tmp_ctrl.get("epsilon").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_f64().unwrap_or(1.0e-5)},
                other => {1.0e-5},
            };
            geometric.subfrctor = match tmp_ctrl.get("subfrctor").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => {tmp_num.as_i64().unwrap_or(1) as i32},
                other => {1},
            };
            geometric.usedmax = match tmp_ctrl.get("usedmax").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(s) => *s,
                other => false,
            };
            geometric.frequency = match tmp_ctrl.get("frequency").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(s) => *s,
                other => true,
            };
            geometric.thermo = match tmp_ctrl.get("thermo").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Array(s) => {
                    [s[0].as_f64().unwrap_or(300.0), s[1].as_f64().unwrap_or(1.0)]
                },
                other => [300.0, 1.0],
            };
            geometric.analytic_hessian = match tmp_ctrl.get("analytic_hessian").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(b) => *b,
                other => false,
            };
            geometric.use_analdrv = match tmp_ctrl.get("use_analdrv").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Bool(b) => Some(*b),
                other => None,
            };
            geometric.fac = match tmp_ctrl.get("fac").unwrap_or(&serde_json::Value::Null) {
                serde_json::Value::Number(tmp_num) => tmp_num.as_f64(),
                other => None,
            };
            return Ok(Some(geometric));
        },
        other => {
            return Ok(None);
        },
    }
    
}