use std::fs;
use std::io::Write;
use crate::utilities::convert_scientific_notation_to_fortran_format as r2f;
use rest_libcint::{CINTR2CDATA, CintType};
use regex::Regex;
use crate::constants::{SPECIES_INFO};
use crate::external_libs::py2fch;
use crate::scf_io::SCF;
use crate::scf_io::SCFType;
use crate::x2c::RelativisticMethod;
use tensors::MatrixFull;


macro_rules! dump_real_r2f {
    ($input:expr, $data:expr) => {
    let mut i_index = 0;
    $data.iter().for_each(|x| {
        let sdd = format!("{:16.8E}", x);
        if (i_index + 1)%5 == 0 {
            write!($input, "{}\n",r2f(&sdd))
        } else {
            write!($input, "{}",r2f(&sdd))
        };
        i_index += 1;
    });
    if i_index % 5 != 0 {write!($input, "\n");}
}
}

macro_rules! dump_int {
    ($input:expr, $data:expr) => {
    let mut i_index = 0;
    $data.iter().for_each(|x| {
        if (i_index + 1)%6 == 0 {
            write!($input, "{:12}\n", x)
        } else {
            write!($input, "{:12}", x)
        };
        i_index += 1;
    });
    if i_index % 6 != 0 {write!($input, "\n");}
}
}


impl SCF {
    pub fn save_fchk_of_gaussian(&self) {
        println!("\nSave fch file");
        self.create_fchk_head();
        self.fchk_write_mo();
        // the DH density dump (see `SCF::dh_rdm1_resp`)
        if let Some(sections) = self.dh_rdm1_resp.as_ref() {
            let labels = ["Total MP2 Density", "Spin MP2 Density"];
            for (label, dm) in labels.iter().zip(sections.iter()) {
                self.fchk_append_density_ao(label, dm);
            }
        }
    }

    pub fn create_fchk_head(&self) {
        let re_basis = Regex::new(r"/?(?P<basis>[^/]*)/?$").unwrap();
        let cap = re_basis.captures(&self.mol.ctrl.basis_path).unwrap();
        let basis_name = cap.name("basis").unwrap().as_str().to_string();
        let mut input = fs::File::create(&format!("{}.fchk",&self.mol.geom.name)).unwrap();
        write!(input, "{:} generated by REST\n", &self.mol.geom.name);
        if let SCFType::ROHF = self.scftype {
            write!(input, "SP        RO{:-58}{:-20}\n",
                self.mol.ctrl.xc.to_uppercase(),
                basis_name.to_uppercase()
            );
        } else if self.mol.spin_channel==1 {
            write!(input, "SP        R{:-59}{:-20}\n",
                self.mol.ctrl.xc.to_uppercase(),
                basis_name.to_uppercase()
            );
        } else {
            write!(input, "SP      U{:-59}{:-20}\n",
                self.mol.ctrl.xc.to_uppercase(),
                basis_name.to_uppercase()
            );
        };
        let natom = self.mol.geom.elem.len();
        write!(input, "Number of atoms                            I {:16}\n", self.mol.geom.elem.len());
        let mut route_tokens: Vec<String> = vec![String::from("#p")];
        route_tokens.push(format!("{}/{}",
            self.mol.ctrl.xc.to_uppercase(),
            basis_name.to_uppercase()
        ));
        if let Some(disp) = &self.mol.ctrl.empirical_dispersion {
            let em = match disp.as_str() {
                "d3" => "GD3",
                "d3bj" => "GD3BJ",
                "d4" => "GD4",
                other => other,
            };
            route_tokens.push(format!("em={}", em));
        }
        match self.mol.ctrl.rel {
            RelativisticMethod::SFX2C => route_tokens.push(String::from("int(nobasistransform,X2C)")),
            _ => route_tokens.push(String::from("int=nobasistransform")),
        };
        write!(input, "Route                                      C   N={:12}\n", route_tokens.len());
        write!(input, "{}\n", route_tokens.join(" "));
        write!(input, "Charge                                     I {:16}\n", self.mol.ctrl.charge as i32);
        write!(input, "Multiplicity                               I {:16}\n", self.mol.ctrl.spin as i32);
        write!(input, "Number of electrons                        I {:16}\n", self.mol.num_elec[0] as i32);
        write!(input, "Number of alpha electrons                  I {:16}\n", self.mol.num_elec[1] as i32);
        write!(input, "Number of beta electrons                   I {:16}\n", self.mol.num_elec[2] as i32);
        write!(input, "Number of basis functions                  I {:16}\n", self.mol.num_basis);
        write!(input, "Number of independent functions            I {:16}\n", self.mol.num_state);
        // ==============================
        // Now for atomic numbers
        // ==============================
        write!(input, "Atomic numbers                             I   N={:12}\n", natom);
        let mut i_index = 0;
        self.mol.geom.elem.iter().for_each(|x| {
            let (mass, charge) = SPECIES_INFO.get(x.as_str()).unwrap();
            if (i_index + 1)%6 == 0 {
                write!(input, "{:12}\n",*charge as i32)
            } else {
                write!(input, "{:12}",*charge as i32)
            };
            i_index += 1;
        });
        if i_index % 6 != 0 {write!(input, "\n");}
        // ==============================
        // Now for Nuclear charges
        // ==============================
        write!(input, "Nuclear charges                            R   N={:12}\n", natom);
        let mut i_index = 0;
        self.mol.geom.elem.iter().for_each(|x| {
            let (mass, charge) = SPECIES_INFO.get(x.as_str()).unwrap();
            let sdd = format!("{:16.8E}", charge);
            if (i_index + 1)%5 == 0 {
                write!(input, "{}\n",r2f(&sdd))
            } else {
                write!(input, "{}",r2f(&sdd))
            };
            i_index += 1;
        });
        if i_index % 5 != 0 {write!(input, "\n");}
        // ==============================
        // Now for geometry coordinates
        // ==============================
        write!(input, "Current cartesian coordinates              R   N={:12}\n", natom*3);
        let mut i_index = 0;
        self.mol.geom.position.iter_columns_full().for_each(|x_position| {
            x_position.iter().for_each(|x| {
                let sdd = format!("{:16.8E}",x);
                if (i_index + 1)%5 ==0 {
                    write!(input,"{}\n", r2f(&sdd));
                } else {
                    write!(input,"{}",r2f(&sdd));
                }
                i_index +=1;
            })
        });
        if i_index % 5 != 0 {write!(input, "\n");}
        // ==============================
        // Now for atomic weights
        // ==============================
        write!(input, "Real atomic weights                        R   N={:12}\n", natom);
        let mut i_index = 0;
        self.mol.geom.elem.iter().for_each(|x| {
            let (mass, charge) = SPECIES_INFO.get(x.as_str()).unwrap();
            let sdd = format!("{:16.8E}", mass);
            if (i_index + 1)%5 == 0 {
                write!(input, "{}\n",r2f(&sdd))
            } else {
                write!(input, "{}",r2f(&sdd))
            };
            i_index += 1;
        });
        if i_index % 5 != 0 {write!(input, "\n");}
        // ==============================
        // Now for MicOpt
        // ==============================
        write!(input, "MicOpt                                     I   N={:12}\n", natom);
        let mut i_index = 0;
        self.mol.geom.elem.iter().for_each(|x| {
            if (i_index + 1)%6 == 0 {
                write!(input, "{:12}\n", -1)
            } else {
                write!(input, "{:12}", -1)
            };
            i_index += 1;
        });
        if i_index % 6 != 0 {write!(input, "\n");}
        //================================
        // Now for basis set info.
        //================================
        let mut num_contract = 0;
        let mut num_primitiv = 0;
        let mut num_d_shell = 0;
        let mut num_f_shell = 0;
        let mut max_ang = 0;
        let mut max_contract = 0;
        let mut shell_type: Vec<i32> = vec![];
        let mut num_primitiv_vec: Vec<usize> = vec![];
        let mut shell_to_atom_map: Vec<usize> = vec![];
        let mut primitive_exp: Vec<f64> = vec![];
        let mut coord_each_shell: Vec<f64> = vec![];
        let mut coeff_vec:Vec<f64> = vec![];
        let shell_type_fac = match self.mol.cint_type {
            CintType::Spheric => -1,
            CintType::Cartesian => 1,
            // NOTE: Spinor is not yet implemented properly, IGOR 2024-08-18
            CintType::Spinor => 1,
        };
        self.mol.basis4elem.iter().enumerate().for_each(|(i_atom,ibas)| {
            ibas.electron_shells.iter().for_each(|ibascell| {
                //let mut tmp_coeff_vec =  ibascell.coefficients.clone();
                ibascell.coefficients.iter().for_each(|coeff_i| {
                    // De-normalization
                    let mut tmp_coeff_i = coeff_i.clone();
                    let tmp_ang = ibascell.angular_momentum[0];
                    tmp_coeff_i.iter_mut().zip(ibascell.exponents.iter()).for_each(|(i, e)| {
                        *i /= CINTR2CDATA::gto_norm(tmp_ang, *e);
                    });
                    coeff_vec.extend(tmp_coeff_i.iter());
                    num_contract += 1;
                    num_primitiv += ibascell.exponents.len();
                    max_ang = std::cmp::max(max_ang, tmp_ang);
                    max_contract = std::cmp::max(max_contract, ibascell.exponents.len());
                    if ibascell.angular_momentum[0] == 2 {num_d_shell += 1};
                    if ibascell.angular_momentum[0] == 3 {num_f_shell += 1};
                    let tmp_shell_type = if ibascell.angular_momentum[0] == 1 {
                        ibascell.angular_momentum[0]
                    } else {
                        ibascell.angular_momentum[0]*shell_type_fac
                    };
                    shell_type.push(tmp_shell_type);
                    num_primitiv_vec.push(ibascell.exponents.len());
                    shell_to_atom_map.push(i_atom+1);
                    primitive_exp.extend(ibascell.exponents.iter());
                    coord_each_shell.extend(self.mol.geom.rg_position.iter_column(i_atom));
                });
            });
        });
        write!(input, "Int Atom Types                             I   N={:12}\n", natom);
        let mut i_index = 0;
        self.mol.geom.elem.iter().for_each(|x| {
            if (i_index + 1)%6 == 0 {
                write!(input, "{:12}\n", 0)
            } else {
                write!(input, "{:12}", 0)
            };
            i_index += 1;
        });
        if i_index % 6 != 0 {write!(input, "\n");}
        write!(input, "Number of contracted shells                I {:16}\n",num_contract);
        write!(input, "Number of primitive shells                 I {:16}\n",num_primitiv);
        let basis_type = match self.mol.cint_type {
            CintType::Spheric => {
                0
            },
            CintType::Cartesian => {
                1
            },
            CintType::Spinor => {
                panic!("Spinor basis is not yet implemented.")
            }
        };
        write!(input, "Pure/Cartesian d shells                    I {:16}\n", basis_type);
        write!(input, "Pure/Cartesian f shells                    I {:16}\n", basis_type);
        write!(input, "Highest angular momentum                   I {:16}\n", max_ang);
        write!(input, "Largest degree of contraction              I {:16}\n", max_contract);
        // ==============================
        // Now for shell infor.
        // ==============================
        write!(input, "Shell types                                I   N={:12}\n", num_contract);
        dump_int!(input, shell_type);
        write!(input, "Number of primitives per shell             I   N={:12}\n", num_contract);
        dump_int!(input, num_primitiv_vec);
        write!(input, "Shell to atom map                          I   N={:12}\n", num_contract);
        dump_int!(input, shell_to_atom_map);
        write!(input, "Primitive exponents                        R   N={:12}\n", primitive_exp.len());
        dump_real_r2f!(input, primitive_exp);
        write!(input, "Contraction coefficients                   R   N={:12}\n", coeff_vec.len());
        dump_real_r2f!(input, coeff_vec);
//        write!(input, "P(S=P) Contraction coefficients            R   N={:12}\n", coeff_vec.len());
//        let mut i_index = 0;
//        coeff_vec.iter().for_each(|x| {
//            let sdd = format!("{:16.8E}", 0);
//            if (i_index + 1)%5 == 0 {
//                write!(input, "{}\n",r2f(&sdd))
//            } else {
//                write!(input, "{}",r2f(&sdd))
//            };
//            i_index += 1;
//        });
//        if i_index % 5 != 0 {write!(input, "\n");}
        write!(input, "Coordinates of each shell                  R   N={:12}\n", coord_each_shell.len());
        dump_real_r2f!(input, coord_each_shell);
        // ==============================
        // Now for total and orb energies
        // ==============================
        let mut ilsw:Vec<i32> = vec![0;100];
        if self.mol.spin_channel==2 && !matches!(self.scftype, SCFType::ROHF) {
            ilsw[0] = 1
        }
        ilsw[4] = 2;
        ilsw[11] = -1;
        ilsw[12] = 5;
        ilsw[24] = 1;
        ilsw[25] = 1;
        ilsw[32] = 100000;
        ilsw[34] = -1;
        ilsw[45] = 1;
        ilsw[49] = -2000000000;
        ilsw[50] = 1;
        ilsw[56] = 4;
        ilsw[57] = 52;
        ilsw[69] = natom as i32;
        ilsw[71] = 1;  
        write!(input, "Num ILSW                                   I     {:12}\n", 100);
        write!(input, "ILSW                                       I   N={:12}\n", 100);
        dump_int!(input, ilsw);
        // TODO: ECP
        let dd = format!("{:27.15E}", self.scf_energy);
        write!(input, "SCF Energy                                 R {}\n",r2f(&dd));
        write!(input, "Total Energy                               R {}\n",r2f(&dd));
        for i_spin in 0..self.mol.spin_channel {
            if i_spin ==0  {
                write!(input, "Alpha Orbital Energies                     R   N={:12}\n", self.eigenvalues[i_spin].len());
            } else {
                write!(input, "Beta Orbital Energies                      R   N={:12}\n", self.eigenvalues[i_spin].len());
            }
            dump_real_r2f!(input, self.eigenvalues[i_spin]);
            if let SCFType::ROHF = self.scftype { break } // ROHF: alpha == beta
        }
        // ==============================
        // Now for orbital coefficients
        // ==============================
        let nbf = self.mol.num_basis;
        //let nif = self.mol.num_state;
        for i_spin in 0..self.mol.spin_channel {
            if i_spin ==0  {
                write!(input, "Alpha MO coefficients                      R   N={:12}\n", self.eigenvectors[i_spin].data.len());
            } else {
                write!(input, "Beta MO coefficients                       R   N={:12}\n", self.eigenvectors[i_spin].data.len());
            }
            if let SCFType::ROHF = self.scftype { break } // ROHF: alpha == beta
        }
        // ==============================
        // Now for orbital occupations
        // ==============================
        if let SCFType::ROHF = self.scftype {
            // ROHF: merge alpha + beta into single occupation array
            let occ_merged: Vec<f64> = self.occupation[0].iter()
                .zip(self.occupation[1].iter())
                .map(|(a, b)| a + b)
                .collect();
            write!(input, "Alpha Orbital Occupation                   R   N={:12}\n", occ_merged.len());
            dump_real_r2f!(input, occ_merged);
        } else {
            for i_spin in 0..self.mol.spin_channel {
                if i_spin == 0 {
                    write!(input, "Alpha Orbital Occupation                   R   N={:12}\n", self.occupation[i_spin].len());
                } else {
                    write!(input, "Beta Orbital Occupation                    R   N={:12}\n", self.occupation[i_spin].len());
                }
                dump_real_r2f!(input, self.occupation[i_spin]);
            }
        }
        // leave MOs blank, it will be written by librest2fch
        let n_dm = nbf*(nbf+1)/2;
        // Total SCF density: the lower-triangular, column-packed AO density, permuted to
        // Gaussian's AO order so it agrees with the MO coefficients written by librest2fch. For
        // open-shell UHF runs the alpha/beta split is written in Gaussian's convention as
        // `Total SCF Density` (alpha + beta) plus `Spin SCF Density` (alpha - beta); a zero
        // placeholder is kept for ROHF (its fractional occupations have no alpha/beta split).
        // librest2fch only requires the section header to exist and copies the section content
        // verbatim when regenerating the MO coefficients.
        let packed_dm = match self.scftype {
            SCFType::UHF => {
                let dm_total = self.density_matrix[0].clone() + self.density_matrix[1].clone();
                self.fchk_pack_density_ao(&dm_total)
            },
            _ if self.mol.spin_channel == 1 => self.fchk_pack_density_ao(&self.density_matrix[0]),
            _ => vec![0.0f64; n_dm],
        };
        write!(input, "Total SCF Density                          R   N={:12}\n", n_dm);
        dump_real_r2f!(input, packed_dm);
        if let SCFType::UHF = self.scftype {
            let dm_spin = self.density_matrix[0].clone() - self.density_matrix[1].clone();
            let packed_spin = self.fchk_pack_density_ao(&dm_spin);
            write!(input, "Spin SCF Density                           R   N={:12}\n", n_dm);
            dump_real_r2f!(input, packed_spin);
        }
        input.sync_all().unwrap();
    }

    pub fn fchk_write_mo(&self) {
        let nbf = self.mol.num_basis;
        let nif = self.mol.num_state;

        for i_spin in 0..self.mol.spin_channel {
            if i_spin ==0  {
                py2fch(format!("{}.fchk", self.mol.geom.name), nbf, nif, &self.eigenvectors[i_spin].data, 'a', &self.eigenvalues[i_spin], 0, 0);
            } else {
                py2fch(format!("{}.fchk", self.mol.geom.name), nbf, nif, &self.eigenvectors[i_spin].data, 'b', &self.eigenvalues[i_spin], 0, 0);
            }
            if let SCFType::ROHF = self.scftype { break } // ROHF: alpha == beta
        }
    }

    /// AO-position permutation from REST's (libcint) AO order to Gaussian's internal order,
    /// as `perm[gaussian_position] = rest_position`, consistent with the permutation that
    /// librest2fch (`py2fch`) applies to the MO coefficients: spherical shells with `l >= 2`
    /// are reordered from libcint's m = -l ... +l to Gaussian's m = 0, +1, -1, +2, -2, ...
    /// (the MOKIT `py2fch_permute_5d/7f/9g/11h` tables); s and p shells carry identical
    /// orders in both conventions, so they are copied through.
    ///
    /// Any density matrix dumped to the fchk file (e.g. the `Total MP2 Density` section)
    /// must be permuted with this table to agree with the MO coefficients of the same file.
    pub fn gaussian_ao_permutation(&self) -> Vec<usize> {
        if !matches!(self.mol.cint_type, CintType::Spheric) {
            panic!("The Gaussian AO permutation is currently implemented for spherical shells only.")
        }
        let mut perm: Vec<usize> = Vec::new();
        let mut base = 0usize;
        self.mol.basis4elem.iter().for_each(|ibas| {
            ibas.electron_shells.iter().for_each(|ibascell| {
                let l = ibascell.angular_momentum[0];
                let n_func = (2 * l + 1) as usize;
                if l <= 1 {
                    (0..n_func).for_each(|i| perm.push(base + i));
                } else {
                    // Gaussian m sequence 0, +1, -1, +2, -2, ...; libcint's m-ascending
                    // position of m is (m + l) within the shell
                    let mut ms: Vec<i32> = vec![0];
                    let mut k = 1i32;
                    while ms.len() < n_func {
                        ms.push(k);
                        if ms.len() < n_func {
                            ms.push(-k);
                        }
                        k += 1;
                    }
                    ms.iter().for_each(|&m| perm.push(base + (m + l as i32) as usize));
                }
                base += n_func;
            })
        });
        perm
    }

    /// Append a symmetric density section to the Gaussian fchk file: `label` followed by the
    /// lower-triangular (column-packed) density in Gaussian's AO order — the same layout as
    /// the `Total SCF Density` section. The file must already exist (i.e.
    /// [`SCF::save_fchk_of_gaussian`] must have run, so the appended section comes after the
    /// librest2fch-written MO coefficients, which are untouched). `label` should follow
    /// Gaussian's section naming ("Total MP2 Density", the name Gaussian itself writes for
    /// the relaxed MP2 density with `Density=MP2`), so that downstream readers (Gaussian
    /// tooling, Multiwfn, MOKIT, ...) recognize the section.
    pub fn fchk_append_density_section(&self, label: &str, packed_lower: &[f64]) {
        println!("\nAppend density section \"{label}\" to fchk file");
        let mut input = fs::OpenOptions::new()
            .append(true)
            .open(format!("{}.fchk", &self.mol.geom.name))
            .unwrap();
        write!(input, "{label:<43}R   N={:12}\n", packed_lower.len());
        dump_real_r2f!(input, packed_lower);
        input.sync_all().unwrap();
    }

    /// Permute an AO-basis density matrix into Gaussian's AO order (consistent with the MO
    /// coefficients of the same fchk file) and pack its lower triangle by column — the layout
    /// of the fchk density sections (same as `Total SCF Density`).
    fn fchk_pack_density_ao(&self, dm_ao: &MatrixFull<f64>) -> Vec<f64> {
        let nbf = dm_ao.size[0];
        assert_eq!(dm_ao.size[1], nbf, "The packed AO density must be square.");
        let perm = self.gaussian_ao_permutation();
        assert_eq!(perm.len(), nbf, "AO permutation size mismatch.");
        let mut packed = Vec::with_capacity(nbf * (nbf + 1) / 2);
        for pj in 0..nbf {
            let j = perm[pj];
            for pi in 0..=pj {
                packed.push(dm_ao.data[perm[pi] + j * nbf]);
            }
        }
        packed
    }

    /// Append a symmetric AO-basis density as the Gaussian fchk density section `label`
    /// (e.g. `Total MP2 Density`): the density is permuted into Gaussian's AO order, packed
    /// lower-triangular by column and appended through [`SCF::fchk_append_density_section`]
    /// (which documents the file/label requirements).
    pub fn fchk_append_density_ao(&self, label: &str, dm_ao: &MatrixFull<f64>) {
        let packed = self.fchk_pack_density_ao(dm_ao);
        self.fchk_append_density_section(label, &packed);
    }

}