[ctrl]
print_level = 1
xc = "hf"
eri_type = "ri_v"
basis_path = "/home/cfh/rest_workspace/rest/basis-set-pool/sto-3g"
basis_type = "Cartesian"
use_auxbas = true
even_tempered_basis = false
charge = 0.0
spin = 1.0
spin_polarization = false
num_threads = 4
run_lib_rint = true

[geom]
name = "H2O"
unit = "angstrom"
position = [
    "O    0.0000000000   0.0000000000   0.0000000000",
    "H    0.7586020000   0.0000000000   0.5042840000",
    "H   -0.7586020000   0.0000000000   0.5042840000",
]
