//! Block Krylov subspace solver for `(1 + A) x = b`.
//!
//! The convergence behavior should approximately matches PySCF's `lib.krylov` block algorithm: each
//! cycle adds the surviving trial directions to the subspace, and the basis is kept non-normalized
//! so that the squared norms of the new trial vectors act as the convergence signal without
//! requiring an explicit residual evaluation.
//!
//! To bound memory the subspace is capped at `max_space` cycles. When that cap is hit without
//! convergence the solver performs a **hard restart** (GMRES(m)-style): the projected system is
//! solved to obtain the current best approximation, that approximation is folded into a running
//! `x_accum`, the subspace is reset, and the residual `b - (I+A) x_accum` becomes the new RHS.
//!
//! Layout convention is col-major: each right-hand side / basis vector is a **column** of the
//! corresponding matrix. So `b` is shaped `[n, nset]`, the operator maps `[n, nblock] -> [n,
//! nblock]`, and the basis matrices `xs`, `ax` are `[n, nd]` with new vectors appended along axis
//! 1.
//!
//! # Note
//!
//! This file is generated by AI. Though this function has been tested, I have not carefully
//! verified all details.

use super::prelude::*;

/// Solve `(I + aop) x = b` by a block Krylov subspace method with hard restarts.
///
/// # Parameters
///
/// - `aop` : Linear operator. Given a `[n, nblock]` input it must return a `[n, nblock]` output
///   (the action of `A` applied column-wise).
/// - `b` : Right-hand sides, shape `[n, nset]`. Each column is one RHS.
/// - `x0` : Optional initial guess, shape `[n, nset]`. Zero initial guess is used if not provided.
/// - `tol` : Convergence tolerance on `max(||new_trial_vec_i||)`.
/// - `max_cycle` : Maximum **total** number of inner cycles, summed across restarts. Recommended
///   value is 54, and is better to be a multiple (or much larger) than `max_space`.
/// - `max_space` : Maximum subspace size in cycles before a hard restart is triggered. Typical
///   values are 6..=20, recommended 14 for CP-HF problems. With `max_space >= max_cycle` no restart
///   ever happens (matches the pre-restart behavior). Storage is `O(n * nset * (max_space + 1))`.
/// - `lindep` : Vectors with `||v||^2 < lindep` are dropped from the subspace.
///
/// # Returns
///
/// `x` of shape `[n, nset]`, an approximate solution of `(I + aop) x = b`.
pub fn krylov_block(
    mut aop: impl FnMut(TsrView) -> Tsr,
    b: TsrView,
    x0: Option<TsrView>,
    tol: f64,
    max_cycle: usize,
    max_space: usize,
    lindep: f64,
) -> Tsr {
    let device = b.device().clone();
    let n = b.shape()[0];
    let nset = b.shape()[1];

    let b_orig = b.to_owned();

    // x_accum plays the role of a running initial guess that is refined on each
    // hard restart. After every restart we re-form the residual b - (I+A) x_accum
    // and rebuild the Krylov subspace from scratch.
    let mut x_accum: Tsr = match x0.as_ref() {
        Some(x0v) => x0v.to_owned(),
        None => rt::zeros(([n, nset], &device)),
    };

    // Pre-allocate basis storage at the bounded restart size. The slabs are
    // overwritten in place on each restart by resetting `nd = 0`.
    let max_basis = nset * (max_space + 1);
    let mut xs: Tsr = rt::zeros(([n, max_basis], &device));
    let mut ax: Tsr = rt::zeros(([n, max_basis], &device));
    let mut all_innerprod: Vec<f64> = Vec::with_capacity(max_basis);

    let conv_thresh = lindep.max(tol * tol);

    let mut total_cycles: usize = 0;
    let mut restart_idx: usize = 0;

    // We must remember the last completed inner loop's subspace and the residual
    // that produced it, so that the final projected solve uses a consistent pair.
    let mut last_nd: usize = 0;
    let mut last_b: Tsr = b_orig.clone();
    // Track the most recent convergence signal so we can detect non-convergence
    // at the end. Initialised to 0.0 so the "empty residual" early-exit at the
    // top of the outer loop is treated as already-converged.
    let mut last_max_innerprod: f64 = 0.0;

    while total_cycles < max_cycle {
        // Form this restart's RHS: b - (I+A) x_accum. On the first pass with no
        // initial guess this is just b (skip the extra aop evaluation).
        let b_residual: Tsr =
            if restart_idx == 0 && x0.is_none() { b_orig.clone() } else { &b_orig - (&x_accum + aop(x_accum.view())) };

        // Orthogonalize the columns of the residual.
        let (mut x1, mut innerprod) = orth_block(b_residual.view(), lindep);

        if x1.shape()[1] == 0 {
            // Residual is already (numerically) zero; x_accum is the answer.
            last_nd = 0;
            last_b = b_residual;
            break;
        }

        // Reset the subspace for this restart.
        all_innerprod.clear();
        let mut nd: usize = 0;
        let mut inner_converged = false;

        for inner in 0..max_space {
            if total_cycles >= max_cycle {
                break;
            }
            total_cycles += 1;
            let nblock = x1.shape()[1];

            let axt = aop(x1.view());

            xs.i_mut((.., nd..nd + nblock)).assign(&x1);
            ax.i_mut((.., nd..nd + nblock)).assign(&axt);
            all_innerprod.extend_from_slice(&innerprod);
            nd += nblock;

            // Orthogonalize axt against the full subspace; same algebra as before.
            let xs_slc = xs.i((.., ..nd));
            let ip_vec = rt::asarray((&all_innerprod, &device));
            let coeffs = (xs_slc.t() % &axt) / ip_vec.i((.., None));
            let x1_new = axt - &xs_slc % &coeffs;

            // MGS new directions: keep at the numerical-zero floor; defer
            // the user's lindep filter so borderline vectors still feed
            // the projected solve via xs / ax.
            let (mut next_x1, mut next_ip) = orth_block(x1_new.view(), lindep);

            // Convergence test uses the unfiltered max innerprod.
            let max_innerprod = next_ip.iter().copied().fold(0.0_f64, f64::max);
            let r = max_innerprod.sqrt();

            // Filter the next-iteration directions to those above conv_thresh.
            let keep_mask: Vec<bool> = next_ip.iter().map(|&ip| ip > conv_thresh).collect();
            if keep_mask.iter().any(|&b| !b) {
                next_x1 = next_x1.bool_select(1, &keep_mask);
                next_ip = keep_mask
                    .iter()
                    .zip(next_ip.iter())
                    .filter_map(|(&m, &ip)| if m { Some(ip) } else { None })
                    .collect();
            }

            // Per-element diagnostics on the new trial block.
            let l2_per_elem = (max_innerprod / (n as f64)).sqrt();
            let max_abs: f64 = x1_new.iter().fold(0.0_f64, |acc, &v| acc.max(v.abs()));

            println!(
                "krylov restart {} inner {} (total cycle {}): max(||v||^2) = {:.3e}, max(||v||) = {:.3e}, per-elem L2 = {:.3e}, max-abs = {:.3e}",
                restart_idx, inner + 1, total_cycles, max_innerprod, r, l2_per_elem, max_abs,
            );

            x1 = next_x1;
            innerprod = next_ip;
            last_max_innerprod = max_innerprod;

            if max_innerprod < conv_thresh {
                inner_converged = true;
                break;
            }
        }

        last_nd = nd;
        last_b = b_residual;

        if inner_converged || total_cycles >= max_cycle {
            break;
        }

        // Hard restart: solve the projected system, fold x_partial into x_accum,
        // discard the subspace, and continue the outer loop.
        let x_partial = projected_solve(xs.i((.., ..nd)), ax.i((.., ..nd)), &all_innerprod, last_b.view());
        x_accum += &x_partial;
        restart_idx += 1;
        println!("---- restart {restart_idx}: x_accum refined, subspace reset ----");
    }

    // Final projected solve on the last subspace, using the matching residual.
    let x_out: Tsr = if last_nd == 0 {
        x_accum
    } else {
        let x_final = projected_solve(xs.i((.., ..last_nd)), ax.i((.., ..last_nd)), &all_innerprod, last_b.view());
        x_accum + x_final
    };

    // Hard fail on non-convergence: a silently unconverged x propagates as a
    // subtly wrong Hessian downstream, which is worse than crashing here.
    if last_max_innerprod >= conv_thresh {
        panic!(
            "krylov_block failed to converge: max(||v||^2) = {:.3e} >= tol^2 = {:.3e} after {} cycles \
             ({} restarts, max_cycle = {}, max_space = {}). Increase max_cycle or check the operator.",
            last_max_innerprod, conv_thresh, total_cycles, restart_idx, max_cycle, max_space,
        );
    }

    x_out
}

/// Solve the projected `(I + A_proj) c = g` system and reconstruct `Xs c`.
///
/// `xs_slc` and `ax_slc` are the subspace and its image under A, both `[n, nd]`. `inner` is the
/// per-column squared norm of `xs_slc` (length `nd`). `b_proj_src` is the RHS that produced this
/// subspace; the returned tensor has shape `[n, nset]`.
fn projected_solve(xs_slc: TsrView, ax_slc: TsrView, inner: &[f64], b_proj_src: TsrView) -> Tsr {
    let nd = xs_slc.shape()[1];
    // h[i, j] = (xs.T @ ax)[i, j] + delta_ij * ||xs[:, i]||^2
    let mut h: Tsr = xs_slc.t() % &ax_slc;
    for i in 0..nd {
        h[[i, i]] += inner[i];
    }
    // g[i, k] = (xs.T @ b)[i, k]
    let g: Tsr = xs_slc.t() % &b_proj_src;
    let c = rt::linalg::solve_general((h, g));
    &xs_slc % &c
}

/// Modified Gram-Schmidt over the **columns** of `vec`, keeping non-normalized
/// orthogonal vectors and tracking their squared norms. Mirrors `_orth_block`
/// in the Python prototype (which operated on rows; here we operate on columns
/// because the rest of the solver is col-major).
///
/// Columns whose remaining squared norm falls below `lindep` are dropped.
///
/// Returns `(out, norms_sq)` where `out` has shape `[n, m]` with `m <= nblock`.
fn orth_block(vec: TsrView, lindep: f64) -> (Tsr, Vec<f64>) {
    let device = vec.device().clone();
    let n = vec.shape()[0];
    let nblock = vec.shape()[1];

    let mut result: Vec<Tsr> = Vec::with_capacity(nblock);
    let mut norms_sq: Vec<f64> = Vec::with_capacity(nblock);

    for i in 0..nblock {
        let mut vi: Tsr = vec.i((.., i)).to_owned();
        for j in 0..result.len() {
            let coeff = (&vi % &result[j]).to_scalar() / norms_sq[j];
            vi -= coeff * &result[j];
        }
        let nsq = (&vi % &vi).to_scalar();
        if nsq > lindep {
            result.push(vi);
            norms_sq.push(nsq);
        }
    }

    // stack vectors to output matrix if any survived
    if result.is_empty() {
        // rt::stack does not allow zero-length, where numpy also disallowed.
        (rt::zeros(([n, 0], &device)), norms_sq)
    } else {
        (rt::stack((result, -1)), norms_sq)
    }
}
